print("CS151 Lab 0")
print("Laure")
print("Laure is 18")
print ("Laure has 4 pets")
print("Laure likes the color green")
print("Laure is current in a computer science class")
print("Laure has brown hair")